---
- name: MariaDB Automation on a VM (CentOS 7)
  hosts: databases
  tasks:
    # This part is not necessary if we are using a pre-built instance
    # I am using qemu-kvm to create a VM with Centos 7
    #  - name: Create a VM on AWS
    #    include_tasks: ec2.yml

    # Install MariaDB 10.5 on the VM
    - name: Install MariaDB
      yum:
        name: mariadb-server_10.5.8-1.el7.centos.x86_64.rpm
        state: present

    # Start and enable MariaDB service
    - name: Start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes

    # Create a new database named "internship"
    - name: Create "internship" database
      mysql_db:
        name: internship
        state: present

    # Create a new user named "intern" with password "intern" with SELECT privilege only to all tables.

    - name: User and privilege settings
      mysql_user:
        name: intern
        password: intern
        priv: "internship.*:SELECT"
        state: present

    - name: Create "interviews" table
      mysql_db:
        name: internship
        state: import
        target: sql/interviews.sql
